### ISSUE TITLE
Incorrect result handling for _beginthreadex() (Windows)

### ISSUE THREAD

**Issue by BigJim** [moteus/lua-llthreads2#12]
If you look at MSDN you'll see that _beginthreadex() returns a thread handle on success. But on error it will return either -1 or an 0.
So your logic of "  if(INVALID_THREAD == this->thread){  rc = -1;  }" will produce incorrect results expected below "if (rc == 0)" as success (as is correctly from the Linux version).

To fix this, I replaced that code with a single line:
rc = (((intptr_t) pthis->thread <= 0) ? -1 : 0);

Also I moved llthread_validate() at the bottom of the "if(rc == 0)" condition since we now know there is only a thread to validate only inside of it.

Refs:
https://msdn.microsoft.com/en-us/library/kdzttdcb.aspx
http://man7.org/linux/man-pages/man3/pthread_create.3.html

Thanks for this great Lua extension.  It's an improvement of the original Lua llthreads that appears to be no longer maintained.

**Comment by BigJim** [comment]
Probably didn't make clear. Your new fix misses the 3rd/correct case where "this->thread > 0" (a valid handle) rc should equal 0.
Why I suggested the conditional "rc = (((intptr_t) pthis->thread <= 0) ? -1 : 0);" which covers all three cases.

Thanks again.

**Comment by moteus** [comment]
`rc` value [init with 0](https://github.com/moteus/lua-llthreads2/blob/master/src/llthread.c#L378)
So for Windows it will be either `-1` or `0`.
For pthreads it will be result of `pthread_create`
