### ISSUE TITLE
Can main thread know what was happening in child thread?

### ISSUE THREAD

**Issue by imuzi** [moteus/lua-llthreads2#4]
First to say, my english is poor ,forgive me for making  mistakes.

What i want is running something block  in child thread ,like a status machine. when status changed , in main thread listener , i will keep check the status , and do something like  ui fresh.

like i said ,all i want is the main thread could know what was happening in child thread when child thread is running , but i cant't ,is there any way to solve it.  

Besides, if there is any lib can do that ?

**Comment by moteus** [comment]
I use my lzmq library for that.

```Lua
local zthreads = require "lzmq.threads"

local thread = zthreads.xactor(function(pipe)
  while true do
    .... 
    pipe:send('NEW STATE')
    ....
  end
end):start()

---
--- You can use `lzmq.poller` or use thread:socket():fd() to poll work thread
while true do
  print(thread:recv())
end
```
For example this is poller based on LibUV - https://github.com/moteus/lua-lluv-poll-zmq.
Also you can use any other socket library

**Comment by imuzi** [comment]
Thank you  very much for replied me !
Great ! lua-lluv-poll-zmq. is good and powerful,i am happy to know this lib from your sharing!
Before i saw this , i found a lib called lua-chan -https://github.com/easeway/lua-chan,using  this lib i can send string between threads, which is enough for me,i don't know if it can be run on android,still testing my logic.
you are a great guy ,thanks again !
