### ISSUE TITLE
Does it works on android?Any help would mean a lot!

### ISSUE THREAD

**Issue by imuzi** [moteus/lua-llthreads2#6]
Ndk build is passed，now i met a new problem ， subthread is not running !
It works perfect on ios !
I tried to turn off the luajit on android ,still seems no effective.
Below is the test code !
Ps: I also tested the luaproc and llthread,both met the same problem ,no log info printed.

```lua
 local llthread= require "llthread2" 
  local thread_code = [[ 
    print("CHILD: received params:", ...) 
    return ...
]] 
local thread = llthreads.new(thread_code, "number:", 1234, "nil:", nil, "bool:", true) 
assert(thread:start(true))
```

**Comment by moteus** [comment]
I never use Android. 
According docs linker should not link with pthread.
Try remove external deps from rockspec file.

**Comment by moteus** [comment]
Can you please tell did you can make it work
